# Generated by Django 5.2.3 on 2025-06-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
