# Generated by Django 5.2.3 on 2025-06-23 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0004_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
    ]
