# Generated by Django 5.2.3 on 2025-06-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_workerservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerService',
        ),
    ]
