# Generated by Django 5.2.3 on 2025-06-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
