# Generated by Django 5.2.3 on 2025-06-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_workermessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerMessage',
        ),
    ]
